### PR TITLE
Big endian issues (+ Snow Leopard)

### LINKED ISSUE #1958: Some questions about "dds_stream_write_keyBE"
The 211 line of "dds_cdrstream.h"  "dds_stream_write_keyBE" have five  parameters， but in the 3983 line of "dds_cdrstream.c" have four parameters, I want to know why this is based on the big end and small end mentioned above， thank you very much!

### LINKED ISSUE #2019: Build failure: `ddsi_udp.c: error: storage size of 'mreqn' isn't known` etc.
Build fails on earlier macOS with the following errors:
```
[  9%] Building C object src/tools/idlpp/CMakeFiles/idlpp.dir/src/main.c.o
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/tools/idlpp && /opt/local/bin/gcc-mp-13 -DHAVE_CONFIG_H=1 -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/tools/idlpp/src -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/tools/idlpp/src -pipe -Os -DNDEBUG -I/opt/local/include -std=gnu99 -arch ppc -mmacosx-version-min=10.6 -fPIC -Wall -Wextra -Wconversion -Wmissing-prototypes -MD -MT src/tools/idlpp/CMakeFiles/idlpp.dir/src/main.c.o -MF CMakeFiles/idlpp.dir/src/main.c.o.d -o CMakeFiles/idlpp.dir/src/main.c.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/tools/idlpp/src/main.c
[  9%] Building C object src/tools/idlpp/CMakeFiles/idlpp.dir/src/mbchar.c.o
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/tools/idlpp && /opt/local/bin/gcc-mp-13 -DHAVE_CONFIG_H=1 -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/tools/idlpp/src -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/tools/idlpp/src -pipe -Os -DNDEBUG -I/opt/local/include -std=gnu99 -arch ppc -mmacosx-version-min=10.6 -fPIC -Wall -Wextra -Wconversion -Wmissing-prototypes -MD -MT src/tools/idlpp/CMakeFiles/idlpp.dir/src/mbchar.c.o -MF CMakeFiles/idlpp.dir/src/mbchar.c.o.d -o CMakeFiles/idlpp.dir/src/mbchar.c.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/tools/idlpp/src/mbchar.c
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c: In function 'set_mc_options_transmit_ipv4_if':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:391:21: error: storage size of 'mreqn' isn't known
  391 |     struct ip_mreqn mreqn;
      |                     ^~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:391:21: warning: unused variable 'mreqn' [-Wunused-variable]
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c: In function 'joinleave_ssm_mcgroup':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:637:29: error: storage size of 'gsr' isn't known
  637 |     struct group_source_req gsr;
      |                             ^~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:642:57: error: 'MCAST_JOIN_SOURCE_GROUP' undeclared (first use in this function)
  642 |     rc = ddsrt_setsockopt (socket, IPPROTO_IPV6, join ? MCAST_JOIN_SOURCE_GROUP : MCAST_LEAVE_SOURCE_GROUP, &gsr, sizeof (gsr));
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:642:57: note: each undeclared identifier is reported only once for each function it appears in
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:642:83: error: 'MCAST_LEAVE_SOURCE_GROUP' undeclared (first use in this function)
  642 |     rc = ddsrt_setsockopt (socket, IPPROTO_IPV6, join ? MCAST_JOIN_SOURCE_GROUP : MCAST_LEAVE_SOURCE_GROUP, &gsr, sizeof (gsr));
      |                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:637:29: warning: unused variable 'gsr' [-Wunused-variable]
  637 |     struct group_source_req gsr;
      |                             ^~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:647:27: error: storage size of 'mreq' isn't known
  647 |     struct ip_mreq_source mreq;
      |                           ^~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:655:55: error: 'IP_ADD_SOURCE_MEMBERSHIP' undeclared (first use in this function); did you mean 'IP_ADD_MEMBERSHIP'?
  655 |     rc = ddsrt_setsockopt (socket, IPPROTO_IP, join ? IP_ADD_SOURCE_MEMBERSHIP : IP_DROP_SOURCE_MEMBERSHIP, &mreq, sizeof (mreq));
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                                       IP_ADD_MEMBERSHIP
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:655:82: error: 'IP_DROP_SOURCE_MEMBERSHIP' undeclared (first use in this function); did you mean 'IP_DROP_MEMBERSHIP'?
  655 |     rc = ddsrt_setsockopt (socket, IPPROTO_IP, join ? IP_ADD_SOURCE_MEMBERSHIP : IP_DROP_SOURCE_MEMBERSHIP, &mreq, sizeof (mreq));
      |                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                  IP_DROP_MEMBERSHIP
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/core/ddsi/src/ddsi_udp.c:647:27: warning: unused variable 'mreq' [-Wunused-variable]
  647 |     struct ip_mreq_source mreq;
      |                           ^~~~
make[2]: *** [src/core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_udp.c.o] Error 1
. . .
[ 28%] Building C object src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/time/darwin/time.c.o
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt && /opt/local/bin/gcc-mp-13  -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/ddsrt-internal/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/include -pipe -Os -DNDEBUG -I/opt/local/include -std=gnu99 -arch ppc -mmacosx-version-min=10.6 -Wall -Wextra -Wconversion -Wmissing-prototypes -MD -MT src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/time/darwin/time.c.o -MF CMakeFiles/ddsrt-internal.dir/src/time/darwin/time.c.o.d -o CMakeFiles/ddsrt-internal.dir/src/time/darwin/time.c.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/time/darwin/time.c
/opt/local/bin/gcc-mp-13 -pipe -Os -DNDEBUG -I/opt/local/include -arch ppc -mmacosx-version-min=10.6 -dynamiclib -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names -current_version 0.10.5 -o ../../lib/libcycloneddsidl.0.10.5.dylib -install_name @rpath/libcycloneddsidl.0.dylib CMakeFiles/idl.dir/src/symbol.c.o CMakeFiles/idl.dir/src/directive.c.o CMakeFiles/idl.dir/src/expression.c.o CMakeFiles/idl.dir/src/file.c.o CMakeFiles/idl.dir/src/processor.c.o CMakeFiles/idl.dir/src/scanner.c.o CMakeFiles/idl.dir/src/string.c.o CMakeFiles/idl.dir/src/annotation.c.o CMakeFiles/idl.dir/src/scope.c.o CMakeFiles/idl.dir/src/tree.c.o CMakeFiles/idl.dir/src/visit.c.o CMakeFiles/idl.dir/src/print.c.o CMakeFiles/idl.dir/src/keylist.c.o CMakeFiles/idl.dir/src/hashid.c.o CMakeFiles/idl.dir/src/parser.c.o CMakeFiles/idl.dir/src/md5.c.o  -Wl,-rpath,@loader_path/../lib
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/threads/posix/threads.c: In function 'ddsrt_thread_getname':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/threads/posix/threads.c:74:12: error: 'MAXTHREADNAMESIZE' undeclared (first use in this function)
   74 |   char buf[MAXTHREADNAMESIZE + 1] = "";
      |            ^~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/threads/posix/threads.c:74:12: note: each undeclared identifier is reported only once for each function it appears in
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/threads/posix/threads.c:74:8: warning: unused variable 'buf' [-Wunused-variable]
   74 |   char buf[MAXTHREADNAMESIZE + 1] = "";
      |        ^~~
[ 29%] Building C object src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/rusage/posix/rusage.c.o
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt && /opt/local/bin/gcc-mp-13  -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/ddsrt-internal/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/include -pipe -Os -DNDEBUG -I/opt/local/include -std=gnu99 -arch ppc -mmacosx-version-min=10.6 -Wall -Wextra -Wconversion -Wmissing-prototypes -MD -MT src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/rusage/posix/rusage.c.o -MF CMakeFiles/ddsrt-internal.dir/src/rusage/posix/rusage.c.o.d -o CMakeFiles/ddsrt-internal.dir/src/rusage/posix/rusage.c.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/rusage/posix/rusage.c
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/threads/posix/threads.c: In function 'ddsrt_gettid':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/threads/posix/threads.c:356:3: warning: implicit declaration of function 'pthread_threadid_np'; did you mean 'pthread_is_threaded_np'? [-Wimplicit-function-declaration]
  356 |   pthread_threadid_np(NULL, &tid);
      |   ^~~~~~~~~~~~~~~~~~~
      |   pthread_is_threaded_np
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/threads/posix/threads.c: In function 'ddsrt_gettid_for_thread':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/threads/posix/threads.c:369:10: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  369 |   return (ddsrt_tid_t) thread.v;
      |          ^
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/time/darwin/time.c: In function 'ddsrt_time_monotonic':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-0.10.5/src/ddsrt/src/time/darwin/time.c:65:28: warning: conversion to 'long long int' from 'uint64_t' {aka 'long long unsigned int'} may change the sign of the result [-Wsign-conversion]
   65 |   return (ddsrt_mtime_t) { mt * timeInfo.numer / timeInfo.denom };
      |                            ^~
make[2]: *** [src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/threads/posix/threads.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

We do have a fix for missing `pthread_is_threaded_np`. I am not sure about the rest though at the moment.

### PR DESCRIPTION
**Pull request by eboasson**
This makes Cyclone build and run its test suite on big-endian machines again. This is based on running the tests on Linux on a 64-bit power architecture machine. The Snow Leopard build fixes were taken from #2020 as agreed.

Fixes #1958
Fixes #2019 
Fixes #2020 

@barracuda156 perhaps you can give it a try?

### CODE REVIEW

**Comment by barracuda156** [comment]
@eboasson Sure, I will run the build now and let you know.

**Comment by barracuda156** [comment]
@eboasson If I run it from f23e45b079eb80fdd66b175068317bcc5fdb9b3e commit, it fails here:
```
[ 15%] Building C object src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/environ/posix/environ.c.o
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt && /opt/local/bin/gcc-mp-13  -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/ddsrt-internal/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/ddsrt/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/ddsrt/src -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/include -pipe -Os -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -std=gnu99 -arch ppc -mmacosx-version-min=10.6 -Wall -Wextra -Wconversion -Wmissing-prototypes -MD -MT src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/environ/posix/environ.c.o -MF CMakeFiles/ddsrt-internal.dir/src/environ/posix/environ.c.o.d -o CMakeFiles/ddsrt-internal.dir/src/environ/posix/environ.c.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/ddsrt/src/environ/posix/environ.c
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c: In function 'ddsi_udp_conn_read':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:138:23: error: field 'ip4' has incomplete type
  138 |     struct in_pktinfo ip4;
      |                       ^~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c: In function 'joinleave_ssm_mcgroup':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:768:29: error: storage size of 'gsr' isn't known
  768 |     struct group_source_req gsr;
      |                             ^~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:773:57: error: 'MCAST_JOIN_SOURCE_GROUP' undeclared (first use in this function)
  773 |     rc = ddsrt_setsockopt (socket, IPPROTO_IPV6, join ? MCAST_JOIN_SOURCE_GROUP : MCAST_LEAVE_SOURCE_GROUP, &gsr, sizeof (gsr));
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:773:57: note: each undeclared identifier is reported only once for each function it appears in
[ 15%] Building C object src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/filesystem/posix/filesystem.c.o
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:773:83: error: 'MCAST_LEAVE_SOURCE_GROUP' undeclared (first use in this function)
  773 |     rc = ddsrt_setsockopt (socket, IPPROTO_IPV6, join ? MCAST_JOIN_SOURCE_GROUP : MCAST_LEAVE_SOURCE_GROUP, &gsr, sizeof (gsr));
      |                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:768:29: warning: unused variable 'gsr' [-Wunused-variable]
  768 |     struct group_source_req gsr;
      |                             ^~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:778:27: error: storage size of 'mreq' isn't known
  778 |     struct ip_mreq_source mreq;
      |                           ^~~~
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt && /opt/local/bin/gcc-mp-13  -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/ddsrt-internal/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/ddsrt/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/ddsrt/src -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/include -pipe -Os -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -std=gnu99 -arch ppc -mmacosx-version-min=10.6 -Wall -Wextra -Wconversion -Wmissing-prototypes -MD -MT src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/filesystem/posix/filesystem.c.o -MF CMakeFiles/ddsrt-internal.dir/src/filesystem/posix/filesystem.c.o.d -o CMakeFiles/ddsrt-internal.dir/src/filesystem/posix/filesystem.c.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/ddsrt/src/filesystem/posix/filesystem.c
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:786:55: error: 'IP_ADD_SOURCE_MEMBERSHIP' undeclared (first use in this function); did you mean 'IP_ADD_MEMBERSHIP'?
  786 |     rc = ddsrt_setsockopt (socket, IPPROTO_IP, join ? IP_ADD_SOURCE_MEMBERSHIP : IP_DROP_SOURCE_MEMBERSHIP, &mreq, sizeof (mreq));
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                                       IP_ADD_MEMBERSHIP
[ 16%] Building C object src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/process/posix/process.c.o
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt && /opt/local/bin/gcc-mp-13  -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/ddsrt-internal/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/ddsrt/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/ddsrt/src -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/build/src/ddsrt/include -pipe -Os -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -std=gnu99 -arch ppc -mmacosx-version-min=10.6 -Wall -Wextra -Wconversion -Wmissing-prototypes -MD -MT src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/process/posix/process.c.o -MF CMakeFiles/ddsrt-internal.dir/src/process/posix/process.c.o.d -o CMakeFiles/ddsrt-internal.dir/src/process/posix/process.c.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/ddsrt/src/process/posix/process.c
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:786:82: error: 'IP_DROP_SOURCE_MEMBERSHIP' undeclared (first use in this function); did you mean 'IP_DROP_MEMBERSHIP'?
  786 |     rc = ddsrt_setsockopt (socket, IPPROTO_IP, join ? IP_ADD_SOURCE_MEMBERSHIP : IP_DROP_SOURCE_MEMBERSHIP, &mreq, sizeof (mreq));
      |                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                  IP_DROP_MEMBERSHIP
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:778:27: warning: unused variable 'mreq' [-Wunused-variable]
  778 |     struct ip_mreq_source mreq;
      |                           ^~~~
[ 16%] Building C object src/ddsrt/CMakeFiles/ddsrt-internal.dir/src/random/posix/random.c.o
make[2]: *** [src/core/CMakeFiles/ddsc.dir/ddsi/src/ddsi_udp.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
(This is not directly comparable with the earlier successful build, since that was of 0.10.5 and not from the master.)

Passing `-DENABLE_IPV6=0 -DENABLE_SOURCE_SPECIFIC_MULTICAST=0` still leaves it with the error:
```
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c: In function 'ddsi_udp_conn_read':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:138:23: error: field 'ip4' has incomplete type
  138 |     struct in_pktinfo ip4;
      |                       ^~~
```

But this looks rather like an SDK issue, not endianness.

**Comment by eboasson** [comment]
Right, I should try to effectively do `-DENABLE_IPV6=0 -DENABLE_SOURCE_SPECIFIC_MULTICAST=0` automatically, it is just one more check using the availability macros.

> ```
> /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c: In function 'ddsi_udp_conn_read':
> /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_cyclonedds/cyclonedds/work/cyclonedds-f23e45b079eb80fdd66b175068317bcc5fdb9b3e/src/core/ddsi/src/ddsi_udp.c:138:23: error: field 'ip4' has incomplete type
>   138 |     struct in_pktinfo ip4;
>       |                       ^~~
> ```

We can live without that one, I'll have a look on how can I most easily avoid needing it.

**Comment by barracuda156** [comment]
In principle IPV6 was supported from 10.5, so it should work, but perhaps not everything needed is available in the SDK or, possibly, is available under a different name. But this is not something I know well myself.

File: src/core/ddsi/include/dds/ddsi/ddsi_config.h [hunk 1]
```diff
@@ -400,7 +400,7 @@ struct ddsi_config
   int retry_on_reject_besteffort;
   int generate_keyhash;
   uint32_t max_sample_size;
-  bool extended_packet_info;
+  int extended_packet_info;
```
Comment (barracuda156) [inline src/core/ddsi/include/dds/ddsi/ddsi_config.h:403]: (A rare case where it would not break things on macOS ppc, since there bool is 4-byte. Usually bools are nightmare, since they are assumed to be 1 byte, but this is not necessarily true.)

File: src/core/cdr/src/dds_cdrstream.c [hunk 2]
```diff
@@ -3682,6 +3690,7 @@ static void dds_stream_extract_keyBE_from_key_prim_op (dds_istream_t * __restric
     }
   }
 }
+#endif
```
Comment (dpotman) [inline src/core/cdr/src/dds_cdrstream.c:3693]: The `#if` on line 3668 can be removed, not that the function is LE only

File: src/core/ddsc/tests/serdata_keys.c [hunk 3]
```diff
@@ -337,6 +337,11 @@ static void check_key_keyhash (struct dds_serdata_default *sd,
 }
 
 // FIXME: the CDR used in this test assumes running on a little-endian machine
```
Comment (dpotman) [inline src/core/ddsc/tests/serdata_keys.c:339]: This is fixed now 😄

**Review by dpotman — APPROVED** [review]
LGTM! Only some nitpicking below

File: src/core/ddsi/include/dds/ddsi/ddsi_config.h (hunk 1 above)
Comment (eboasson) [reply src/core/ddsi/include/dds/ddsi/ddsi_config.h:403]: Cool! I didn't know yet that macOS PPC mapped bool to 32 bits ...

**Comment by eboasson** [comment]
@barracuda156 I just pushed a few updates. It now tries to auto-detect IPv6 and source-specific multicast in CMake and adapt accordingly (I won't do any checking if it is disabled by the user, so you might want to throw away `CMakeCache.txt` to check).

I tried to change the `IP_PKTINFO` related code to avoid it on snow leopard. Not sure if it'll work.

Perhaps you can give it another go?

@dpotman Thanks for catching those two things 😀 I feel really stupid for fixing the thing mentioned in the FIXME and then not removing the FIXME itself ... 🤦🤣

**Comment by eboasson** [comment]
@barracuda156 I'm going to merge this as it does fix the big-endian issues (at least in my testing). Hopefully the latest changes make it work out-of-the-box on Snow Leopard as well. If not, please just create a new issue. Thanks!

**Comment by barracuda156** [comment]
@eboasson Thank you! I will try it tonight and let you know.

**Comment by barracuda156** [comment]
@eboasson Yes, from 1deaa93b2019e6e23cb34d73594fc25327d6966c it builds without any patches and configure args. Thank you!

**Comment by barracuda156** [comment]
@eboasson BTW, could you make a new release? I generated a patch, diffing master and 0.10.5, and it is 200k+ LoC and 9.5 MB, that won't be accepted :)
